{{- $fullName := .Values.deployment.name }}
{{- $svcPort := .Values.service.port -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $fullName }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ $fullName }}